[package]
name = "markings"
version = "0.2.0"
authors = ["museun <museun@outlook.com>"]
description = "a very simple string (template) replacement crate"
repository = "https://github.com/museun/markings"
edition = "2018"
license = "0BSD"
keywords = ["template"]
